version: '3'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: dormitory
    ports:
      - "5433:5433"

volumes:
  postgres_data: